//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAREIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.queues = new HashSet<queue>();
        }
    
        public int Id_patient { get; set; }
        public string name_patient { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public Nullable<int> fk_id_insurance { get; set; }
        public string code_insurance { get; set; }
        public string code_identity { get; set; }
    
        public virtual insurance insurance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<queue> queues { get; set; }
    }
}
