//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAREIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class queue
    {
        public int Id_queue { get; set; }
        public Nullable<int> fk_id_patient { get; set; }
        public System.DateTimeOffset time_queue { get; set; }
        public string status_queue { get; set; }
        public Nullable<int> type_queue { get; set; }
    
        public virtual patient patient { get; set; }
    }
}
