//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAREIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int Id_transaction { get; set; }
        public Nullable<int> fk_id_employee { get; set; }
        public Nullable<int> fk_id_medicine { get; set; }
        public Nullable<int> qty_medicine { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.DateTimeOffset> time { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual medicine medicine { get; set; }
    }
}
